version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  web:
    build: ./app
    container_name: flask-app
    restart: always
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=userpass
      - DB_NAME=mydb

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - appnet

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
